### PR TITLE
Add withHeaders(Map) to Response

### PR DESCRIPTION
**Pull request by rouzwawi**
fix for #11

### CODE REVIEW

**Comment by rouzwawi** [comment]
@cjhawley

**Comment by pettermahlen** [comment]
I wonder if we should have two methods ```withAddedHeaders``` and ```withHeaders```. As it is, there's no way to set the headers for the response to some exact map, and also no way to clear a header.

**Comment by rouzwawi** [comment]
Is it common that you want all existing headers to be cleared out?

I'm more on the line of reasoning that, if I get a response instance as an argument a method/function, then I expect it to have data in it that is there for a reason, so I would only add to it. If I really needed to discard things, I would have to construct a new response from scratch. But I have not run into the need to clear out headers.

**Comment by pettermahlen** [comment]
I agree that would be the majority use case. I wonder if there are enough exceptions to warrant adding another method. I guess it comes down to writing something like this:

```
  Response<T> incoming = getIncomingResponse(); 
 
  Response<T> realResponse = Response.forStatus(incoming.status())
    .withHeaders(removeHeaderIDontWant(incoming.headers());

  if (incoming.payload().isPresent()) {
    return realResponse.withPayload(incoming.payload.get());
  }

  return realResponse;
```

**Comment by pettermahlen** [comment]
On another note, I just noticed #11 is about Request, not Response

**Comment by rouzwawi** [comment]
oh, so this does not resolve #11 :(

On the headers handling, yes that would be something to write if you're implementing a proxy to a different service. In most cases there will probably be some domain object in between so that the two responses would be a bit separated in the code.

**Comment by rouzwawi** [comment]
oops, I accidentally pushed this to master when pushing ca941c1dc6a284d8815ff207828285265eb151ac

**Pull request merged**
