### PR TITLE
Bump junit-bom to 5.7.0

### PR DESCRIPTION
**Pull request by honnix**
See issue here: https://github.com/junit-team/junit4/issues/1678

### CODE REVIEW

**Comment by honnix** [comment]
This is weird:

```
[INFO] +- org.junit.vintage:junit-vintage-engine:jar:5.7.0:test
...
[INFO] |  \- junit:junit:jar:4.12:test
```

But https://mvnrepository.com/artifact/org.junit.vintage/junit-vintage-engine/5.7.0

**Comment by honnix** [comment]
It is the jackson-bom.

**Comment by honnix** [comment]
https://issues.apache.org/jira/browse/MNG-5600 😢

**Comment by honnix** [comment]
@patriknordlen PTAL. Not sure why coverage check complains though.

**Comment by klaraward** [comment]
@honnix This is still relevant right? (The coverage checks are unfortunately a bit flaky)

**Comment by honnix** [comment]
@klaraward I think this is still valid since the suggestion in junit-team/junit4#1678 is to upgrade. I will need to take another look what this is really about, because it's been a while. :D

**Comment by honnix** [comment]
The coverage under java8 seems very broken and this worries me. I will take a deeper look at it.

**Comment by honnix** [comment]
https://github.com/spotify/styx/pull/884 was a related change.

**Comment by klaraward** [comment]
@honnix Are you happy with us merging #336 instead?

**Comment by honnix** [comment]
Of course! Please go ahead.

**Pull request closed without merging**
