### PR TITLE
Create set-up.svg

### PR DESCRIPTION
**Pull request by zalenski**

### CODE REVIEW

**Comment by rouzwawi** [comment]
:+1:

**Comment by rouzwawi** [comment]
Maybe add some explaining text too? Or is it all self-explaining?

**Comment by zalenski** [comment]
> Maybe add some explaining text too?

Yes, just trying to include the svg.
Looks like you can't do it in the main README.md from github.io [[1]](http://stackoverflow.com/a/21521184).
But you can link to cdn.rawgit.com with a full path [[2]](http://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown/32449263#32449263).

**Comment by rouzwawi** [comment]
Hmm, but isn't github.io the github pages domain? A relative link in the repo would generate a github.com link right? Doesn't that work?

**Comment by zalenski** [comment]
> Doesn't that work?

Don't think so:
```
[![Apollo set-up](website/source/set-up.svg)](website/source/set-up.svg)
[![Apollo in runtime](website/source/runtime.svg)](website/source/runtime.svg)
```

[Apollo set-up](website/source/set-up.svg)
[Apollo in runtime](website/source/runtime.svg)

There's a whole discussion in the SO question,
  http://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown
(the links above are two of the replies there)

**Comment by zalenski** [comment]
> Or is it all self-explaining?

Yes :)

**Pull request merged**
