### PR TITLE
use latest ffwd client lib

### PR DESCRIPTION
**Pull request by ckiosidis**
bumped ffwd-http-client to 0.4.2

### CODE REVIEW

**Comment by lepistone** [comment]
@ckiosidis Thanks for the PR. The build fails because Missinglink detects a problem with dependencies. Can you please look into this?

**Comment by lmuhlha** [comment]
@ckiosidis Was there something that led you to need the version bumped? I'd like to remove the dependency entirely: https://github.com/spotify/apollo/pull/314

**Comment by ckiosidis** [comment]
Hey @lmuhlha I wanted to bump the version to get rid of the shaded jackson dependency, which caused some issues to a service I am maintaining.
No objection with removing it completely 👍 

@lepistone thanks for letting me know

**Comment by lepistone** [comment]
Thank you!

**Pull request closed without merging**
