### PR TITLE
Fall back to domain if apollo.{backend,domain} are unset

### PR DESCRIPTION
**Pull request by dflemstr**
@rouzwawi @pettermahlen @zalenski @mbruggmann

### CODE REVIEW

**Comment by mbruggmann** [comment]
:+1:

**Comment by rouzwawi** [comment]
:+1:

**Comment by rouzwawi** [comment]
A test maybe

**Comment by dflemstr** [comment]
@rouzwawi tests added

**Comment by rouzwawi** [comment]
`mvn license:update-file-header`

**Comment by dflemstr** [comment]
I haven't touched this code base in too long, I'm getting rusty :)

**Pull request merged**
