### PR TITLE
use FOSS root pom

### PR DESCRIPTION
**Pull request by pettermahlen**
Clean up some stuff from the parent POM in this project.

### CODE REVIEW

**Comment by pettermahlen** [comment]
@rouzwawi look good?

**Comment by rouzwawi** [comment]
Nice. Does the failsafe plugin get bound by default? The same with enforcer. Seems some plugins were completely removed. Maybe that was intentional.

**Comment by pettermahlen** [comment]
The build section of the pom still has this: 
```
        <plugins>
            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.eluder.coveralls</groupId>
                <artifactId>coveralls-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
```

When I run `mvn verify`, they both run, so that looks OK to me.

**Comment by pettermahlen** [comment]
I guess we could remove the coveralls plugin though?

**Comment by rouzwawi** [comment]
Aha I missed that.

Isn't coveralls running?

**Comment by pettermahlen** [comment]
It might be, but we're using codecov.io these days, so AFAIK, coveralls no longer fulfils a need?

**Comment by rouzwawi** [comment]
That's right. Confused those two. This is way too "early" in the morning for me :)

**Pull request merged**
